apiVersion: v1
kind: Service
metadata:
  labels:
    app: http-test
  name: http-test
spec:
  ports:
  - name: 8080-to-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: http-test
  type: ClusterIP
status:
  loadBalancer: {}
