apiVersion: v1
kind: Pod
metadata:
  name: aws-pod
  namespace: default
  labels:
    env: test
    cloud: aws
spec:
  serviceAccountName: aws-sa
  containers:
    - name: awscli
      image: amazon/aws-cli:2.34.58
      command:
        - sleep
        - infinity
